### ISSUE TITLE
Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by crescentrose** [ClaudeBot/hubot-steam-webapi#6]
Hi!

After installing the hubot-steam-webapi package with npm, I get this error: 

```
Sat Jan 02 2016 10:36:34 GMT-0500 (EST)] ERROR Unable to load /home/ivan/nano/node_modules/hubot-steam-webapi/src/steam: Error: Could not locate the bindings file. Tried:
 → /home/ivan/nano/node_modules/ref/build/binding.node
 → /home/ivan/nano/node_modules/ref/build/Debug/binding.node
 → /home/ivan/nano/node_modules/ref/build/Release/binding.node
 → /home/ivan/nano/node_modules/ref/out/Debug/binding.node
 → /home/ivan/nano/node_modules/ref/Debug/binding.node
 → /home/ivan/nano/node_modules/ref/out/Release/binding.node
 → /home/ivan/nano/node_modules/ref/Release/binding.node
 → /home/ivan/nano/node_modules/ref/build/default/binding.node
 → /home/ivan/nano/node_modules/ref/compiled/4.2.4/linux/x64/binding.node
  at bindings (/home/ivan/nano/node_modules/bindings/bindings.js:88:9)
  at Object.<anonymous> (/home/ivan/nano/node_modules/ref/lib/ref.js:5:47)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (/home/ivan/nano/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/home/ivan/nano/node_modules/hubot-steam-webapi/src/steam.coffee:25:1, <js>:10:3)
  at Object.<anonymous> (/home/ivan/nano/node_modules/hubot-steam-webapi/src/steam.coffee:21:1, <js>:327:4)
  at Module._compile (module.js:435:26)
  at Object.loadFile (/home/ivan/nano/node_modules/coffee-script/lib/coffee-script/coffee-script.js:182:19)
  at Module.load (/home/ivan/nano/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Robot.loadFile (/home/ivan/nano/node_modules/hubot/src/robot.coffee:353:9, <js>:221:20)
  at module.exports (/home/ivan/nano/node_modules/hubot-steam-webapi/index.coffee:11:9, <js>:24:31)
  at Robot.loadExternalScripts (/home/ivan/nano/node_modules/hubot/src/robot.coffee:399:11, <js>:269:39)
  at /home/ivan/nano/node_modules/hubot/bin/hubot:121:11, <js>:127:26
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

I've tried reinstalling and rebuilding the package but no luck. Any ideas?

**Comment by MrSaints** [comment]
Hey, it looks like a Node related issue.

Can you try running the following:

```
sudo npm install -g node-gyp
```

Also, what version of Node are you on?

**Comment by crescentrose** [comment]
That did it! Sorry it took me a while, my VPS has limited memory so I had to set up swap to get it to compile. My Node version is v4.2.4. Thank you a lot for your help!
